// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iofshnigmuxlxciymldk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZnNobmlnbXV4bHhjaXltbGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTE2NjIsImV4cCI6MjA2NjU4NzY2Mn0.FRW2owD1YTrEeXQNrH3f-7lJ-Nb0SbhkmyaAajDYn1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);